services:
  postgres:
    image: postgres:15
    container_name: spokenarr-postgres
    environment:
      POSTGRES_USER: spokenarr
      POSTGRES_PASSWORD: spokenarr_pass
      POSTGRES_DB: spokenarr
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  spokenarr-api:
    build: ./backend
    image: nate8727/spokenarr-api:latest
    container_name: spokenarr-api
    environment:
      - DATABASE_URL=postgresql://spokenarr:spokenarr_pass@postgres:5432/spokenarr
    depends_on:
      - postgres
    ports:
      - "5180:80"
    restart: unless-stopped

  spokenarr-web:
    build: ./frontend
    image: nate8727/spokenarr-web:latest
    container_name: spokenarr-web
    environment:
      - API_URL=http://spokenarr-api:80
    depends_on:
      - spokenarr-api
    ports:
      - "6006:6006"  # Storybook UI
    restart: unless-stopped

volumes:
  pgdata:
