services:
  postgres:
    image: postgres:15
    container_name: spokenarr-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-spokenarr}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-spokenarr_pass}
      POSTGRES_DB: ${POSTGRES_DB:-spokenarr}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  spokenarr-api:
    build: ./backend
    env_file:
      - .env
    image: nate8727/spokenarr-api:latest
    container_name: spokenarr-api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SETTINGS_PATH=/app/config/settings.json
    depends_on:
      - postgres
    ports:
      - "${API_HOST_PORT:-5080}:80"
    volumes:
      - ./backend/app:/app/app:ro
    restart: unless-stopped

  spokenarr-web:
    build: ./frontend
    image: nate8727/spokenarr-web:latest
    container_name: spokenarr-web
    environment:
      - STORYBOOK_DISABLE_TELEMETRY=true
      - NODE_ENV=development
    depends_on:
      - spokenarr-api
    ports:
      - "6080:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  pgdata:
